name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: yarn --version
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: install
        run: yarn install --frozen-lockfile --prefer-offline
      - name: format
        run: yarn format
      - name: lint
        run: yarn run lint
      - name: audit
        if: (${{ success() }} || ${{ failure() }})
        run: yarn audit
      - name: test
        if: (${{ success() }} || ${{ failure() }})
        run: yarn test:self
